spring.application.name=EndpointApp
# spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

# FIX H2 Console
spring.datasource.url=jdbc:mysql://localhost:3306/recommendation?useSSL=false&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.show-sql=true